const healthyRecipes = {
  recipes: [
    {
      id: "egy1",
      title: "Fava with Olive Oil & Lemon",
      publisher: "Amira's Pantry",
      source_url: "https://amiraspantry.com/egyptian-ful-medames-recipe/",
      image_url: "https://www.themediterraneandish.com/wp-content/uploads/2020/01/foul-mudammas-recipe-6.jpg",
      servings: 2,
      cooking_time: 15,
      ingredients: [
        { quantity: 1, unit: "cup", description: "Cooked fava beans" },
        { quantity: 1, unit: "tbsp", description: "Olive oil" },
        { quantity: 0.5, unit: "", description: "Lemon juice" },
        { quantity: null, unit: "", description: "Salt and pepper" },
      ],
    },
    {
      id: "egy2",
      title: "Tahini Salad",
      publisher: "Feel Good Foodie",
      source_url: "https://feelgoodfoodie.net/recipe/tahini-salad-dressing/",
      image_url: "https://amiraspantry.com/wp-content/uploads/2020/11/tahini-paste-I-1024x1024.jpg",
      servings: 4,
      cooking_time: 10,
      ingredients: [
        { quantity: 4, unit: "tbsp", description: "Tahini" },
        { quantity: 2, unit: "tbsp", description: "Lemon juice" },
        { quantity: 1, unit: "clove", description: "Crushed garlic" },
        { quantity: null, unit: "", description: "Salt and pepper" },
        { quantity: null, unit: "", description: "Water to thin" },
      ],
    },
    {
      id: "egy3",
      title: "Healthy Egyptian Koshari",
      publisher: "Amira's Pantry",
      source_url: "https://amiraspantry.com/koshari-recipe/",
      image_url: "https://silkroadrecipes.com/wp-content/uploads/2021/06/Egyptian-Koshari-square-500x375.jpg",
      servings: 4,
      cooking_time: 40,
      ingredients: [
        { quantity: 1, unit: "cup", description: "Brown lentils" },
        { quantity: 1, unit: "cup", description: "Brown rice" },
        { quantity: 1, unit: "cup", description: "Whole wheat pasta" },
        { quantity: 2, unit: "cups", description: "Baked crispy onions" },
        { quantity: 1, unit: "cup", description: "Natural tomato sauce" },
      ],
    },
    {
      id: "egy4",
      title: "Light Green Molokhia",
      publisher: "Feel Good Foodie",
      source_url: "https://feelgoodfoodie.net/recipe/egyptian-molokhia/",
      image_url: "https://ujamaaseeds.com/cdn/shop/files/iStock-1490936409.jpg?v=1735415906",
      servings: 3,
      cooking_time: 25,
      ingredients: [
        { quantity: 400, unit: "g", description: "Chopped molokhia leaves" },
        { quantity: 3, unit: "cups", description: "Chicken broth" },
        { quantity: 3, unit: "cloves", description: "Garlic, minced" },
        { quantity: 1, unit: "tbsp", description: "Dried coriander" },
      ],
    },
    {
      id: "egy5",
      title: "Egyptian Tabbouleh Salad",
      publisher: "BBC Good Food",
      source_url: "https://www.bbcgoodfood.com/recipes/tabbouleh",
      image_url: "https://thishealthytable.com/wp-content/uploads/2024/03/tabouli-salad-recipe-735x735.jpg",
      servings: 4,
      cooking_time: 20,
      ingredients: [
        { quantity: 1, unit: "cup", description: "Soaked bulgur" },
        { quantity: 2, unit: "cups", description: "Chopped parsley" },
        { quantity: 0.5, unit: "cup", description: "Chopped tomatoes" },
        { quantity: 0.25, unit: "cup", description: "Lemon juice" },
        { quantity: 2, unit: "tbsp", description: "Olive oil" },
      ],
    },
    {
      id: "egy6",
      title: "Grilled Fish with Lemon",
      publisher: "AllRecipes",
      source_url: "https://www.allrecipes.com/recipe/228319/grilled-fish-with-garlic-lemon/",
      image_url: "https://www.nyfjournal.com/wp-content/uploads/2014/05/Grilled-Whole-Red-Snapper-3-Served-with-Lemon.jpg",
      servings: 2,
      cooking_time: 30,
      ingredients: [
        { quantity: 2, unit: "fillets", description: "Mullet fish" },
        { quantity: 2, unit: "tbsp", description: "Lemon juice" },
        { quantity: 1, unit: "tbsp", description: "Olive oil" },
        { quantity: 1, unit: "tsp", description: "Cumin" },
      ],
    },
    {
      id: "egy7",
      title: "Yellow Lentil Soup",
      publisher: "Feel Good Foodie",
      source_url: "https://feelgoodfoodie.net/recipe/egyptian-lentil-soup/",
      image_url: "https://images.cookforyourlife.org/wp-content/uploads/2018/08/shutterstock_309501530-min.jpg",
      servings: 4,
      cooking_time: 35,
      ingredients: [
        { quantity: 1, unit: "cup", description: "Yellow lentils" },
        { quantity: 1, unit: "cup", description: "Grated carrots" },
        { quantity: 1, unit: "cup", description: "Onion" },
        { quantity: 1, unit: "tsp", description: "Cumin" },
      ],
    },
    {
      id: "egy8",
      title: "Cucumber Yogurt Salad",
      publisher: "Amira's Pantry",
      source_url: "https://amiraspantry.com/cucumber-yogurt-salad/",
      image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0",
      servings: 2,
      cooking_time: 10,
      ingredients: [
        { quantity: 1, unit: "cup", description: "Low-fat yogurt" },
        { quantity: 1, unit: "cup", description: "Grated cucumber" },
        { quantity: 1, unit: "clove", description: "Crushed garlic" },
        { quantity: 0.25, unit: "tsp", description: "Salt" },
      ],
    },
    {
      id: "egy9",
      title: "Grilled Eggplant with Tahini",
      publisher: "Feel Good Foodie",
      source_url: "https://feelgoodfoodie.net/recipe/baba-ghanoush/",
      image_url: "https://thelemonbowl.com/wp-content/uploads/2020/10/Grilled-Eggplant-with-Tahini-Sauce.jpg",
      cooking_time: 25,
      ingredients: [
        { quantity: 2, unit: "", description: "Large grilled eggplants" },
        { quantity: 3, unit: "tbsp", description: "Tahini" },
        { quantity: 2, unit: "tbsp", description: "Lemon juice" },
        { quantity: null, unit: "", description: "Salt and pepper" },
      ],
    },
    {
      id: "egy10",
      title: "Egyptian Vegetable Soup",
      publisher: "Amira's Pantry",
      source_url: "https://amiraspantry.com/egyptian-vegetable-soup/",
      image_url: "https://www.laboiteny.com/cdn/shop/articles/Quick_Lentil_Vegetable_Soup.jpg?v=1654995070",
      servings: 5,
      cooking_time: 30,
      ingredients: [
        { quantity: 1, unit: "cup", description: "Chopped carrots" },
        { quantity: 1, unit: "cup", description: "Chopped zucchini" },
        { quantity: 1, unit: "cup", description: "Small potatoes" },
        { quantity: 1, unit: "cup", description: "Celery" },
      ],
    },
  ],
};

export default healthyRecipes;
